apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
  labels:
    app: echoserver
spec:
  containers:
    - name: hello-world
      image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
      env:
        - name: PORT
          value: "8080"
          
